CREATE TABLE IF NOT EXISTS users (
    ID INTEGER NOT NULL PRIMARY KEY,
    Name TEXT NOT NULL,
    Age INTEGER,
);
CREATE TABLE IF NOT EXISTS health_data (
    DataID INTEGER NOT NULL PRIMARY KEY,

) 